apiVersion: skaffold/v4beta13
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: europe-central2-docker.pkg.dev/gogcp-main-7/private-docker-images/gomod/goapp
      context: .
      docker:
        dockerfile: build/goapp/Dockerfile
test:
  - image: europe-central2-docker.pkg.dev/gogcp-main-7/private-docker-images/gomod/goapp
    structureTests:
      - test/goapp/container-structure-test.yaml

profiles:
  - name: dev
    activation:
      - command: dev
      - command: debug
    build:
      local:
        useDockerCLI: true
        push: false
    deploy:
      helm:
        releases:
          - chartPath: deploy/goapp-dev
            name: goapp
            namespace: default
      kubeContext: docker-desktop

  - name: test
    build:
      local:
        useDockerCLI: true
        push: true
    deploy:
      helm:
        releases:
          - chartPath: deploy/goapp-test
            name: goapp
            namespace: gomod-test-7
      kubeContext: gke_gogcp-test-7_europe-central2-a_gogke-test-7
