apiVersion: skaffold/v4beta13
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: europe-central2-docker.pkg.dev/gogcp-main-7/private-docker-images/gomod/goapp
      context: .
      docker:
        dockerfile: build/goapp/Dockerfile
test:
  - image: europe-central2-docker.pkg.dev/gogcp-main-7/private-docker-images/gomod/goapp
    structureTests:
      - test/goapp/container-structure-test.yaml

profiles:
  - name: dev
    activation:
      - command: dev
      - command: debug
    build:
      local:
        useDockerCLI: true
        push: false
        tryImportMissing: false
    manifests:
      kustomize:
        paths:
          - deploy/goapp/overlays/dev
    deploy:
      kubeContext: docker-desktop
      kubectl: {}

  - name: prod-eu1
    build:
      googleCloudBuild:
        projectId: gogcp-main-7
    manifests:
      hooks:
        before: [host: { command: ["scripts/sops/decrypt.bash"] }]
      kustomize:
        paths:
          - deploy/goapp/overlays/prod
    deploy:
      kubeContext: gke_gogcp-test-7_europe-central2-a_gogke-test-7
      kubectl: {}
