apiVersion: v2
name: goapp-test
version: 0.0.0
dependencies:
  - repository: oci://europe-central2-docker.pkg.dev/gogcp-main-7/private-helm-charts/gorun/demo
    name: stateless-kuard
    version: 0.7.101
